    name: Publish Vite React App to GitHub Pages

    on:
      push:
        branches:
          - master # Change to 'main' if your default branch is 'main'

    jobs:
      build-and-publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20' # Recommended recent LTS Node.js version for Vite
              cache: 'npm'

          - name: Install dependencies
            run: npm install

          - name: Build React App (Vite)
            run: npm run build # This executes the 'build' script defined in package.json, which is 'vite build'

          - name: Publish to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./dist
              force_orphan: true # <-- ADD THIS LINE to ensure a clean branch
    